openapi: 3.0.1
info:
  title: Swagger REST Article
  description: This is the swagger file that goes with our server code
  version: 1.0.0
servers:
- url: /api/v1/
paths:
  /nation:
    get:
      tags:
      - Nation
      summary: The nation data structure supported by the server application
      description: Read all the observation data of the nation
      operationId: handlers.nation.read_all
      parameters:
      - name: startDate
        in: query
        description: The start date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      - name: endDate
        in: query
        description: The end date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      responses:
        200:
          description: Successful read observations data of the nation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Nation'
        400:
          description: startDate and endDate must be in the format YYYY-MM-DD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: startDate must be lower or equal than endDate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /region:
    get:
      tags:
      - Region
      summary: The region data structure supported by the server application
      description: Read all the observation data of all the regions
      operationId: handlers.region.read_all
      parameters:
      - name: startDate
        in: query
        description: The start date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      - name: endDate
        in: query
        description: The end date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      responses:
        200:
          description: Successful read observations data of all  the regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
        400:
          description: startDate and endDate must be in the format YYYY-MM-DD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: startDate must be lower or equal than endDate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /region/{regionName}:
    get:
      tags:
      - Region
      summary: The region data structure supported by the server application
      description: Read all the observation data of a region
      operationId: handlers.region.read_one
      parameters:
      - name: regionName
        in: path
        description: The region name
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: The start date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      - name: endDate
        in: query
        description: The end date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      responses:
        200:
          description: Successful read all the observations data of a region
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
        400:
          description: startDate and endDate must be in the format YYYY-MM-DD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: startDate must be lower or equal than endDate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /province:
    get:
      tags:
      - Province
      summary: The province data structure supported by the server application
      description: Read all the observation data of all the provinces
      operationId: handlers.province.read_all
      parameters:
      - name: startDate
        in: query
        description: The start date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      - name: endDate
        in: query
        description: The end date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      responses:
        200:
          description: Successful read observations data of all the provinces
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Province'
        400:
          description: startDate and endDate must be in the format YYYY-MM-DD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: startDate must be lower or equal than endDate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /province/{provinceName}:
    get:
      tags:
      - Province
      summary: The province data structure supported by the server application
      description: Read all the observation data of a province
      operationId: handlers.province.read_one
      parameters:
      - name: provinceName
        in: path
        description: The province name
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: The start date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      - name: endDate
        in: query
        description: The end date of the observations in the format YYYY-MM-DD
        schema:
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
      responses:
        200:
          description: Successful read observations all the data of a province
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Province'
        400:
          description: startDate and endDate must be in the format YYYY-MM-DD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: startDate must be lower or equal than endDate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Nation:
      type: object
      properties:
        data:
          type: string
          format: date
        stato:
          type: string
        ricoverati_con_sintomi:
          type: integer
        terapia_intensiva:
          type: integer
        totale_ospedalizzati:
          type: integer
        isolamento_domiciliare:
          type: integer
        totale_attualmente_positivi:
          type: integer
        nuovi_attualmente_positivi:
          type: integer
        dimessi_guariti:
          type: integer
        deceduti:
          type: integer
        totale_casi:
          type: integer
        tamponi:
          type: integer
    Region:
      type: object
      properties:
        data:
          type: string
          format: date
        stato:
          type: string
        codice_regione:
          type: integer
        denominazione_regione:
          type: string
        lat:
          type: number
          format: double
        long:
          type: number
          format: double
        ricoverati_con_sintomi:
          type: integer
        terapia_intensiva:
          type: integer
        totale_ospedalizzati:
          type: integer
        isolamento_domiciliare:
          type: integer
        totale_attualmente_positivi:
          type: integer
        nuovi_attualmente_positivi:
          type: integer
        dimessi_guariti:
          type: integer
        deceduti:
          type: integer
        totale_casi:
          type: integer
        tamponi:
          type: integer
    Province:
      type: object
      properties:
        data:
          type: string
          format: date
        stato:
          type: string
        codice_regione:
          type: integer
        denominazione_regione:
          type: string
        codice_provincia:
          type: integer
        denominazione_provincia:
          type: string
        sigla_provincia:
          type: string
        lat:
          type: number
          format: double
        long:
          type: number
          format: double
        totale_casi:
          type: integer
  responses:
    FormatDateError:
      description: startDate and endDate must be in the format YYYY-MM-DD
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    StartEndDateError:
      description: startDate must be lower or equal than endDate
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
